name: "Doppler Environment Loader"
description: "Loads Doppler secrets into the environment as masked values"
inputs:
  doppler-token:
    description: "The Doppler token of the project configuration to be loaded"
    required: true
  debug-prefix:
    description: "The prefix to be used on variables that should not be masked"
    required: false
    default: "DEBUG"
  disable-masking:
    description: "Whether to disable all masking by the action"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Load Doppler secrets
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler-token }}
        DEBUG_PREFIX: ${{ inputs.debug-prefix }}
        DISABLE_MASKING: ${{ inputs.disable-masking }}
      shell: bash
      run: |
        content=$(doppler secrets download --no-file --format env-no-quotes)
        IFS=$'\n'
        for line in $content; do
            key=$(cut -d "=" -f1 <<< $line)
            secret=$(cut -d "=" -f2- <<< $line)
            secret=$(tr -d '\\n' <<< $secret)
            if [[ $DISABLE_MASKING == 'false' && $key != DOPPLER*  && $key != $DEBUG_PREFIX* ]]; then echo "::add-mask::${secret}"; fi
            echo "${key}=${secret}" >> $GITHUB_ENV
        done
        IFS=' '
